In [1]:
import torch

In [2]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# vertical axis is 0, horizontal is 1 by convention

In [3]:
a.ndimension()

2

In [4]:
a.shape

torch.Size([3, 3])

In [5]:
a.size()

torch.Size([3, 3])

In [6]:
a.numel()

9

In [12]:
# indexing works as one would expect
print(a)
print(a[0][0])
print(a[1, 1])
print(a[1, :])
print(a[:, 2])

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor(1.)
tensor(5.)
tensor([4., 5., 6.])
tensor([3., 6., 9.])


In [13]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
b = torch.tensor([[1, 4, 3], [4, 10, 6], [7, 16, 9]], dtype=torch.float32)

a + b

tensor([[ 2.,  6.,  6.],
        [ 8., 15., 12.],
        [14., 24., 18.]])

In [14]:
3 * a

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.],
        [21., 24., 27.]])

In [15]:
a + 1

tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]])

In [18]:
a * b # elementwise product

tensor([[  1.,   8.,   9.],
        [ 16.,  50.,  36.],
        [ 49., 128.,  81.]])

In [21]:
# matrix multiplication
c = torch.tensor([[1, 4, 3], [4, 10, 6]], dtype=torch.float32)
print(torch.mm(a, b))
torch.mm(a, c)

tensor([[ 30.,  72.,  42.],
        [ 66., 162.,  96.],
        [102., 252., 150.]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 2x3)