In [1]:
import torch
from torch import nn, optim
from torch import sigmoid

In [38]:
class OneHiddenLayerNN(nn.Module):
    def __init__(self, D_in, H, D_out):
        super(OneHiddenLayerNN, self).__init__()
        self.hidden_layer_1 = nn.Linear(D_in, H)
        self.out_layer = nn.Linear(H, D_out)

    def forward(self, x):
        z1 = self.hidden_layer_1(x)
        a1 = sigmoid(z1)
        z2 = self.out_layer(a1)
        y_hat = sigmoid(z2)
        return y_hat

In [16]:
model = OneHiddenLayerNN(1, 2, 1)
x = torch.tensor([[1.], [2.], [-42.]])
y_hat = model(x)
print(y_hat)
prediction = torch.round(y_hat)
prediction

tensor([[0.4639],
        [0.4644],
        [0.5057]], grad_fn=<SigmoidBackward0>)


tensor([[0.],
        [0.],
        [1.]], grad_fn=<RoundBackward0>)

In [17]:
model.state_dict()

OrderedDict([('hidden_layer_1.weight',
              tensor([[ 0.9124],
                      [-0.5188]])),
             ('hidden_layer_1.bias', tensor([0.7584, 0.2816])),
             ('out_layer.weight', tensor([[-0.4079, -0.3141]])),
             ('out_layer.bias', tensor([0.3370]))])

In [20]:
# sequential equivalent

from torch.nn import Sequential, Sigmoid, Linear

In [21]:
model = Sequential(Linear(1, 2), Sigmoid(), Linear(2, 1), Sigmoid())
x = torch.tensor([[1.], [2.], [-42.]])
y_hat = model(x)
print(y_hat)
prediction = torch.round(y_hat)
prediction

tensor([[0.4232],
        [0.4166],
        [0.4659]], grad_fn=<SigmoidBackward0>)


tensor([[0.],
        [0.],
        [0.]], grad_fn=<RoundBackward0>)

In [46]:
# training the model

X = torch.arange(-20, 20, 1).view(-1, 1).type(torch.FloatTensor)
Y = torch.zeros(X.shape[0]).view(-1, 1)
Y[(X[:, 0] > -4) & (X[:, 0] < 4)] = 1.0

def train(X, Y, model, optimizer, criterion, epochs=100):
    cost = []
    for epoch in range(epochs):
        total = 0
        for x, y in zip(X, Y):
            y_hat = model(x)
            loss = criterion(y_hat, y)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            total += loss.item()
        cost.append(total)
    return cost

model = OneHiddenLayerNN(1, 2, 1)
optimizer = optim.Adam(model.parameters(), lr=0.01)
criterion = nn.BCELoss()

train(X, Y, model, optimizer, criterion)

[28.714123785495758,
 23.30173361301422,
 20.725814253091812,
 19.555396407842636,
 18.97559230029583,
 18.625965625047684,
 18.38483899831772,
 18.196112513542175,
 18.033079877495766,
 17.882728695869446,
 17.738402381539345,
 17.596497133374214,
 17.45480877161026,
 17.311679862439632,
 17.16550439596176,
 17.014423683285713,
 16.85613625496626,
 16.687863275408745,
 16.506558448076248,
 16.30950716882944,
 16.095161236822605,
 15.863784432411194,
 15.617353864014149,
 15.358788169920444,
 15.091101951897144,
 14.816878758370876,
 14.538095273077488,
 14.256174005568027,
 13.972132503986359,
 13.68675822392106,
 13.400751657783985,
 13.11481099948287,
 12.829664587974548,
 12.546053815633059,
 12.264693062752485,
 11.986232001334429,
 11.711232278496027,
 11.440159659832716,
 11.173386208713055,
 10.911199789494276,
 10.653821274638176,
 10.40141298621893,
 10.154088854789734,
 9.911929875612259,
 9.67498267814517,
 9.443269532173872,
 9.2167923245579,
 8.995538359507918,
 8.7794792

In [69]:
import numpy as np

In [70]:
vals = model(X).detach().numpy()
v1 = np.array([0 if u < 0.5 else 1 for u in vals])
v2 = Y.numpy()

In [71]:
v1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
v2

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [57]:
Y.numpy()

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)