In [1]:
import torch

In [3]:
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

def forward(x):
    y = w * x + b
    return y

x = torch.tensor([[1.0], [2.0]])

y_hat = forward(x)
y_hat

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)

In [4]:
from torch.nn import Linear

In [5]:
torch.manual_seed(42)
model = Linear(in_features=1, out_features=1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7645]], requires_grad=True), Parameter containing:
tensor([0.8300], requires_grad=True)]


In [6]:
x = torch.tensor([0.0])
y_hat = model(x)
y_hat

tensor([0.8300], grad_fn=<AddBackward0>)

In [7]:
x = torch.tensor([[1.0], [2.0]])
y_hat = model(x)
y_hat

tensor([[1.5945],
        [2.3591]], grad_fn=<AddmmBackward0>)

In [8]:
import torch.nn as nn

In [9]:
class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(in_features=input_size, out_features=output_size)

    def forward(self, x):
        out = self.linear(x)
        return out

In [10]:
model = LR(1, 1)

model.state_dict()["linear.weight"].data[0] = torch.tensor([0.5153])
model.state_dict()["linear.bias"].data[0] = torch.tensor([-0.4414])

In [11]:
model.state_dict()

OrderedDict([('linear.weight', tensor([[0.5153]])),
             ('linear.bias', tensor([-0.4414]))])

In [12]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [13]:
x = torch.tensor([[1.0], [2.0]])
y_hat = model(x)
y_hat

tensor([[0.0739],
        [0.5892]], grad_fn=<AddmmBackward0>)